import JSZip from "jszip";

export async function createZipFromResult(result: string): Promise<Blob> {
  const zip = new JSZip();
  zip.file("README.md", "Generated by AI App Generator\n\n");
  zip.file("code/generated-code.txt", result); // or split into multiple files intelligently

  return await zip.generateAsync({ type: "blob" });
}
